### ISSUE TITLE
itemize in description even when string is empty

### ISSUE THREAD

**Issue by eborbath** [loreabad6/R-CV#1]
Hi,

Thanks for making your template publicly available! 

I am having an issue with listing a program in one of the cv entries (education) which misses a description. In this case, I would just like to not have anything there. However, the template includes a bullet, as if there would be an unordered list coming. 

To replicate use the chunk below for education:

```
```{r education}
tribble(
  ~ study, ~ university, ~ loc, ~ dates, ~ details,
  "Doctor of Political and Social Sciences of the European University Institute", "European University Institute","Florence, IT", "09, 2014 - 12, 2018", "Dissertation title: Parties and Protests in Crisis-Hit Europe: Continuity and Change in the Structure of Political Conflict",
  "Doctor of Political and Social Sciences of the European University Institute", "European University Institute","Florence, IT", "09, 2014 - 12, 2018", "Supervisor: Prof. Hanspeter Kriesi",
  "Master of Research in Political and Social Sciences", "","", "09, 2014 - 06, 2015", "") %>% 
  detailed_entries(study, dates, university, loc, details, .protect=FALSE)
```

Which results in:

![demo](https://user-images.githubusercontent.com/9773005/94473268-41925f80-01cc-11eb-9190-034b67f7d5a5.PNG)

I would like the bullet point below my MA to disappear.

I would appreciate if you could take a look!

**Comment by loreabad6** [comment]
Hi @eborbath, yes this is part of the original template available in the {vitae} package. I believe if you want this type of modifications you could always refine the final LaTeX file you get and create the PDF again, then all this details can be errased. I personally like it when everything is automatic, so I try to simply have everything harmonized and just either use bullet point on every entry, or not use bullet points at all. So you could choose to also list your masters dissertation title for example! But of course this is entirely up to you :)

**Comment by eborbath** [comment]
Thanks for your reply. I was hoping that this could be changed by adjusting the awesome-cv.cls with an ifempty statement in the right place. But then I take it from your answer that this is not really possible?

**Comment by loreabad6** [comment]
Good point! I can take a look at later though, but if you want to give it a go, please do!

**Comment by eborbath** [comment]
Yes, I thought the relevant part is where you set the `cvitems` environment, I played a bit with it, but I could not figure it out...

**Comment by loreabad6** [comment]
Yes, `cvitems` should be the place to look at, although I am also wondering if the awesome.tex template could also be altered to get what you want.

**Comment by eborbath** [comment]
But that's the same file no? Or is there another template referenced somewhere?

**Comment by eborbath** [comment]
This has been solved by [mitchelloharawild/vitae/issues/135](https://github.com/mitchelloharawild/vitae/issues/135)
