### ISSUE TITLE
problem with compiling the CV.pdf file

### ISSUE THREAD

**Issue by danielsangarci** [loreabad6/R-CV#2]
Hello Lorena,

First of all let you know the amazing wok you did with your cv template. I really like it!

Some time ago i started using your template with small modifications for my cv as well. But something have changed and i is not posible to compile the CV.pdf file anymore. I have just tried with the code you have here and I get the exact same error i get when i try to compile my CV.

! LaTeX Error: There's no line here to end.

Do you know how this issue could be solved?

Thank you in advance,
Dani

**Comment by loreabad6** [comment]
Hi @danielsangarci, I believe I compile with an old pandoc version and everything seems to work. But I found this issue with your same problem: https://github.com/mitchelloharawild/vitae/issues/229. I will do some tests and come back to you!

**Comment by fgardavaud** [comment]
Hi @loreabad6 ,
First of all, congratulation for such a work. It's wonderful !
See my analyze at https://github.com/mitchelloharawild/vitae/issues/229
@danielsangarci at this time, the unique solution I found is to install an older version of Rstudio.

**Comment by loreabad6** [comment]
Hi @fgardavaud and @danielsangarci, the problem was with passing extra LaTeX packages in the `header-includes` section of the YAML. I now use the `includes` and `in_header` with the [`header.txt`](https://github.com/loreabad6/R-CV/blob/master/header.txt) file, which seems to work fine. I also tested with your Rmd @fgardavaud by chaging the YAML.
cc. @mitchelloharawild

**Comment by fgardavaud** [comment]
@loreabad6 
Great it's work on my side too.
Congratulation for debugging with success and for your reactivity !

**Comment by danielsangarci** [comment]
Hi,
@loreabad6 

Amazing! Thank you so much for you time debugging it!
I guess I missed the notification about you solving the problem. Thank you one more time!

Best,
Dani
